# -*- coding: utf-8 -*-
"""arvoredecisao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpdOiCRBFsLbWpDrnBrEGZJc9ppHLN_m
"""

#Exemplo árvore decisão com Python e sklearn
#Prof. Cloves Rocha IA, AP e AD
 
from sklearn import tree

# ÁREA DE TREINAMENTO 
features = [[100, 1], [150, 1],
           [50, 0], [80, 0]]
labels = [1,1 , 0, 0] # 0 é FRAUDE! e 1 NAO é FRAUDE!

# O classificador encontra padrões nos dados de treinamento

clf = tree.DecisionTreeClassifier() # instância do classificador 
clf = clf.fit(features, labels) # fit encontra padrões nos dados

# iremos utilizar para classificar um bom pagador!
print(clf.predict([[8, 15]]))



