# -*- coding: utf-8 -*-
"""vetores_array_bibliotecas4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/clovesrocha/CFAD2021/blob/main/vetores_array_bibliotecas4.ipynb
"""

# ETE PORTO DIGITAL
# CURSO DE FORMAÇÃO ANALISTA DE DADOS (JÚNIOR E PLENO) 
# PROF.: CLOVES ROCHA
# EXEMPLOS EXTRA DE VETORES E BIBLIOTECAS EM PYTHON: 

import pandas as pd
import numpy as np
import time

vetorestudantes = ['Jorge, Igor, Veruska, Nathália', 10, 9, 8, 7]
print(vetorestudantes)

país = ['Bélgica', 'Índia', 'Brasil']
print(país)

data = {
'País': ['Bélgica', 'Índia', 'Brasil'],
'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
'População': [123465, 456789, 987654]
}
print(data)

df = pd.DataFrame(data, columns=['País','Capital','População'])
print(df)

pd.read_csv('nome_do_arquivo.csv', encoding='ISO-8859-1')
pd.to_csv('nome_do_arquivo_para_salvar.csv')

xlsx = pd.ExcelFile('seu_arquivo_excel.xlsx')
df = pd.read_excel(xlsx, 'Planilha 1')

a = np.array([0, 1, 2, 3])
print(a)

a = time.time()
L = range(1000000)
[i**2 for i in L]
print(time.time() - a)
a = time.time()
b = np.arange(1000000)
b**2
print(time.time() - a)

help(np.array)

a = np.array([0, 1, 2, 3])
a
a.ndim
a.shape
len(a)

b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
b
b.ndim
b.shape
len(b)

c = np.array([[[1], [2]], [[3], [4]]])
c
c.shape

a = np.arange(10) # 0 .. n-1
a
b = np.arange(1, 9, 2) # início, fim (exclusive), passo
b

c = np.linspace(0, 1, 6)   # início, fim, número de pontos
c
d = np.linspace(0, 1, 5, endpoint=False)
d

a = np.ones((3, 3))  # lembrete: (3, 3) é uma tupla
a
b = np.zeros((2, 2))
b
c = np.eye(3)
c
d = np.diag(np.array([1, 2, 3, 4]))
d

a = np.random.rand(4)       # uniforme em [0, 1]
a
b = np.random.randn(4)      # Gaussiana
b
 
np.random.seed(1234)        # Definindo um início

a = np.array([1, 2, 3])
a.dtype
b = np.array([1., 2., 3.])
b.dtype

c = np.array([1, 2, 3], dtype=float)
c.dtype

a = np.ones((3, 3))
a.dtype

d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

e = np.array([True, False, False, True])
e.dtype

f = np.array(['Bonjour', 'Hello', 'Olá',])
f.dtype

# Link exemplo da biblioteca: 
import matplotlib.pyplot as plt
# [1] https://github.com/clovesrocha/ETEPDAD/tree/master/WEBCrawlerPython
# [2] https://github.com/CarlosSMA/ETEPD_AD/blob/main/II_Bimestre/Desafio_I/dados.py